language: python
python: 
  - "3.8"
script: 
  - python test_load_csv.py
  - python test_train_split.py
  - python test_regression_metrics.py
  - python test_classification_metrics.py
  - python KNN/assessment/cross_validation.py
  - python KNN/modelling/generate_predictions.py 
  - python -m pip install coverage
  - python -m coverage report